<?php

namespace Xif\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ActusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActusRepository extends EntityRepository
{
	public function getLasts($num)
	{
		//récupération du query builder
		$queryBuilder = $this->createQueryBuilder('a');

		$queryBuilder
			->setMaxResults((int) $num)
			->orderBy('a.datePublication', 'DESC')
			->innerJoin('a.auteur', 'aut')
			->addSelect('aut');

		//récupération et retour des résultats
		return $queryBuilder->getQuery()->getArrayResult();
	}

	public function countAll()
	{
		$query = $this->_em->createQuery('SELECT COUNT(a) FROM XifCoreBundle:Actus a');
		return $query->getSingleScalarResult();
	}
}
