<?php

namespace Xif\SoundOrganiserBundle\Repository;

/**
 * SongLineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SongLineRepository extends \Doctrine\ORM\EntityRepository {}