<?php

namespace Xif\FileBundle\Repository;

/**
 * FileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileRepository extends \Doctrine\ORM\EntityRepository
{
	public function getWithGroupById($id)
	{
		$qb = $this->createQueryBuilder('f');

		$qb->leftJoin('f.group', 'g')
			->addSelect('g')
			->where('f.id = :id')
			->setParameter('id', (int) $id);

		return $qb->getQuery()->getOneOrNullResult();
	}
}
