<?php

namespace Xif\FileBundle\Repository;

/**
 * MultipleFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MultipleFileRepository extends \Doctrine\ORM\EntityRepository
{
	public function getAllWithFiles()
	{
		$qb = $this->createQueryBuilder('m');

		$this->withFiles($qb);

		return $qb->getQuery()->getResult();
	}

	public function getWithFilesById($id)
	{
		$qb = $this->createQueryBuilder('m');

		$qb->where('m.id = :id')
			->setParameter('id', (int) $id);

		$this->withFiles($qb);

		return $qb->getQuery()->getOneOrNullResult();
	}

	protected function withFiles($qb)
	{
		$qb->leftJoin('m.files', 'f')
			->addSelect('f');
	}
}
