# src/Xif/CoreBundle/Resources/config/routing/actus.yml

# Nouvelle actu
xif_core_newactu:
    path: /new
    defaults:
        _controller: XifCoreBundle:Actus:new
    methods: GET|POST

# Affichage des actus même si elles ne sont plus sur la page d'accueil
xif_core_viewactu:
    path: /{id}
    defaults:
        _controller: XifCoreBundle:Actus:viewOne
    requirements:
        id: \d*
    methods: GET

# Édition des actus
# Tous les administrateurs peuvent les éditer
xif_core_editactu:
    path: /{id}/edit
    defaults:
        _controller: XifCoreBundle:Actus:edit
    requirements:
        id: \d*
    methods: GET|POST
